# ============================================================
# Secure Chat Application Configuration
# Spring Boot 3.x
# ============================================================

# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:8080}
server.address=0.0.0.0

# ===============================
# DATABASE
# ===============================
# Local Run:
# localhost:3306
#
# Docker Compose:
# mysql:3306
#
# Docker automatically overrides this property using
# SPRING_DATASOURCE_URL.

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/secure_chat_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIKARI CONNECTION POOL
# ===============================
spring.datasource.hikari.pool-name=SecureChatPool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.initialization-fail-timeout=1

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Optional
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# MULTIPART FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO

logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

logging.level.org.springframework.web.socket=WARN
logging.level.org.springframework.messaging=WARN
logging.level.org.springframework.messaging.simp=WARN
logging.level.org.springframework.web.SimpLogging=WARN

logging.level.com.secure_chat=INFO

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:be6df5c69f72c6aacfbbd1b4722dafa4aaf397c2003899a0025bd1c54c3e749d}

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.fail-on-empty-beans=false

# ===============================
# SPRING BANNER
# ===============================
spring.main.banner-mode=console

# ===============================
# GRACEFUL SHUTDOWN
# ===============================
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# ===============================
# UTF-8
# ===============================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true